---
title: "GML_Main"
author: "Devin Frost"
date: "2024-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(data.table)
```

# Getting the data

I recommend not running this next chuck, as it takes a lot of RAM and CPU
```{r include=FALSE}
Raw_LCI_Data <- read_csv("game_data_public.LCI.PremierDraft.csv")
DowntoDecks <- Raw_LCI_Data |> select(won, matches("deck_"))
fwrite(DowntoDecks, file = "DowntoDecks", col.names = T, showProgress = T)

```


# Data Exploration

## Checking the overall winrate
```{r}
DowntoDecks <- read_csv("DowntoDecks.csv")
#DowntoDecks |> count(won)

```

Simplified card comparision

```{r}

temp <- DowntoDecks %>% filter(.[[3]] > 0 & .[[3]] > 0) %>% count(won)
temp[[2,2]]/(temp[[2,2]] + temp[[1,2]])


```


```{r}
winrate <- function (c1,c2){
  temp <- DowntoDecks %>% filter(.[[c1]] > 0 & .[[c2]] > 0) %>% count(won)
  if(length(as.matrix(temp)) != 4) {
    return(0)
  }
  return(temp[[2,2]]/(temp[[2,2]] + temp[[1,2]]))
}

#winrate function, card 1, card 2
#only comparing the first card, Abrade to all OTHER cards 
#simplified for my poor laptop
AbradeX <- mapply(winrate, 3, 2:ncol(DowntoDecks), SIMPLIFY = T)
```

DONT RUN THIS
```{r}
RESULT <- data.frame()

for (i in 2:ncol(DowntoDecks)) {
  RESULT <- rbind(RESULT,
                  mapply(winrate, i, 2:ncol(DowntoDecks), SIMPLIFY = T))
}

fwrite(RESULT, file = "DecksGraph.stl", col.names = F, showProgress = T)

```


```{r}
make_graph(RESULT)
```



```{r}
#library(igraph)

graphgraph <- graph_from_adjacency_matrix()
plot.igraph(graphgraph,layout = layout_with_lgl(graphgraph), 
            edge.arrow.size=0.5, vertex.size = 10, vertex.label.cex = 0.1)

```







## looking at the
```{r}
deck_mat <- DowntoDecks[,-1] |> as.matrix() |> as.vector()
zeros <- deck_mat == 0 
deck_mat[zeros] <- NA

deck_mat |> hist()

```



```{python}
for i in range(100):
  print(i)
```

